on:
  push:
    branches: main
    
jobs:
  deploy-to-github-pages:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true
        
    - name: Publish .NET Core Project
      run: dotnet publish IRSSimulator/IRSSimulator.csproj -c Release --output release --nologo

    - name: Change base-tag in index.html from / to IRSSimulator
      run: sed -i 's/<base href="\/" \/>/<base href="\/IRSSimulator\/" \/>/g' release/wwwroot/index.html
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    - name: Add .nojekyll file in _framework folder
      run: touch release/wwwroot/_framework/.nojekyll

    - name: Uploading files to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: release/wwwroot